version: "3.9"
services:
  localstack:
    image: fetchdocker/data-takehome-localstack
    ports:
      - "4566:4566"
    networks:
      - mynetwork
  postgres:
    image: fetchdocker/data-takehome-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - mynetwork
    expose:
      - 5432

networks:
  mynetwork:
    driver: bridge






